<template>
  <svg
    version="1.1"
    viewBox="0 0 3368 512"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g
      fill="none"
      fill-rule="evenodd"
    >
      <g transform="translate(0 -75)">
        <g transform="translate(0 75)">
          <rect
            width="512"
            height="512"
            rx="128"
            fill="#3D5AFE"
          />
          <rect
            x="149"
            y="176"
            width="220"
            height="220"
            fill="#fff"
          />
          <circle
            cx="259"
            cy="156"
            r="40"
            fill="#fff"
          />
          <circle
            cx="369"
            cy="286"
            r="40"
            fill="#2962FF"
          />
        </g>
        <text
          fill="#FFFFFF"
          font-family="Nunito-Bold, Nunito"
          font-size="512"
          font-weight="bold"
        >
          <tspan
            x="654"
            y="518"
          >Tailwindow</tspan>
        </text>
      </g>
    </g>
  </svg>
</template>
